# Datos de conexion al DBMS.
# OJO: la url NO incluye el nombre de la base, porque este programa es el que la crea.
driver=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://localhost:3306/?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
user=root
password=root
