# Datos de conexion a la base creada por el Ejercicio 2
driver=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://localhost:3306/Escuela?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
user=root
password=root

# Registro RMI donde se publica / se busca la Fachada
rmi.host=localhost
rmi.puerto=1099
rmi.nombre=Fachada
